# Generated by Django 5.1.4 on 2026-08-03 16:45

import apps.ambassadors.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0007_store_origin_city_store_origin_complement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbassadorProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots_taken', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Programa de embaixadoras',
                'verbose_name_plural': 'Programa de embaixadoras',
            },
        ),
        migrations.CreateModel(
            name='Ambassador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referral_code', models.CharField(default=apps.ambassadors.models._generate_referral_code, max_length=12, unique=True)),
                ('seat_number', models.PositiveSmallIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Desativa sem apagar o histórico (ex.: loja banida) — os bônus já lançados continuam valendo.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ambassador', to='stores.store')),
            ],
            options={
                'ordering': ['seat_number'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reward_expires_at', models.DateTimeField()),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='ambassadors.ambassador')),
                ('referred_store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ambassador', 'reward_expires_at'], name='ambassadors_ambassa_da30b3_idx')],
            },
        ),
    ]
