# Generated by Django 5.1.4 on 2026-07-19 00:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.CharField(max_length=64)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("underage_suspicion", "Suspeita de menor de idade"),
                            ("sexual_service", "Oferta de serviço sexual"),
                            ("scam", "Golpe/fraude"),
                            ("illegal_content", "Conteúdo ilegal"),
                            ("other", "Outro"),
                        ],
                        max_length=25,
                    ),
                ),
                ("details", models.TextField(blank=True, max_length=1000)),
                ("requires_immediate_action", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModerationQueueItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("store", "Loja"),
                            ("product", "Produto"),
                            ("chat_message", "Mensagem"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_id", models.CharField(max_length=64)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                            ("auto_flagged", "Sinalizado automaticamente"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("automated_flags", models.JSONField(blank=True, default=list)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["decision", "target_type"],
                        name="moderation__decisio_5db2de_idx",
                    )
                ],
            },
        ),
    ]
