# Generated by Django 5.1.4 on 2026-07-19 15:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_reserved_for_product_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payout_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Quanto você quer receber por este item (sem a comissão da plataforma).', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_grams',
            field=models.PositiveIntegerField(help_text='Necessário para cálculo de frete.'),
        ),
    ]
