# Generated by Django 5.1.4 on 2026-07-31 22:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productvideo'),
        ('stores', '0004_simplified_intermediary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAddon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='digital/%Y/%m/')),
                ('label', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.CharField(blank=True, max_length=600)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('physical', 'Item físico (enviado pelo correio)'), ('digital', 'Conteúdo digital (entrega pelo site)'), ('custom', 'Sob encomenda (entrega pelo site)')], db_index=True, default='physical', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='production_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Dias para produzir (só para itens sob encomenda).'),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_grams',
            field=models.PositiveIntegerField(default=0, help_text='Necessário para cálculo de frete.'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['kind', 'status'], name='catalog_pro_kind_828566_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-sold_count'], name='catalog_pro_sold_co_a3f541_idx'),
        ),
        migrations.AddField(
            model_name='productaddon',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productasset',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productquestion',
            name='asked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productquestion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='catalog.product'),
        ),
        migrations.AddIndex(
            model_name='productquestion',
            index=models.Index(fields=['product', 'is_public'], name='catalog_pro_product_5b52a8_idx'),
        ),
    ]
