# Generated by Django 5.1.4 on 2026-08-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productaddon_productasset_productquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Aguardando moderação'), ('published', 'Publicado'), ('rejected', 'Rejeitado'), ('sold', 'Vendido'), ('paused', 'Pausado'), ('removed', 'Removido')], default='draft', max_length=10),
        ),
    ]
