# Generated by Django 5.1.4 on 2026-08-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Texto de abertura da página da categoria (SEO). Sem promessa sanitária nem menção a serviço.', max_length=600),
        ),
    ]
