# Generated by Django 5.1.4 on 2026-08-02 15:27

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='file',
            field=models.ImageField(storage=apps.catalog.models._product_media_storage, upload_to='products/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='file',
            field=models.FileField(storage=apps.catalog.models._product_media_storage, upload_to='products/videos/%Y/%m/'),
        ),
    ]
