# Generated by Django 5.1.4 on 2026-08-02 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_category_description'),
        ('catalog', '0008_product_freight_declared_value'),
    ]

    operations = [
    ]
