# Generated by Django 5.1.4 on 2026-07-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ageverification_validated_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerkyc',
            name='esign_document_ref',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sellerkyc',
            name='esign_provider',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sellerkyc',
            name='esign_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerkyc',
            name='esign_signed_document_url',
            field=models.URLField(blank=True),
        ),
    ]
