# Generated by Django 5.1.4 on 2026-08-01 10:15

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sellerkyc_esign_document_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerkyc',
            name='document_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerkyc',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sellerkyc',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerkyc',
            name='verification_code',
            field=models.CharField(default=apps.accounts.models.generate_kyc_code, editable=False, max_length=12),
        ),
        migrations.AlterField(
            model_name='sellerkyc',
            name='status',
            field=models.CharField(choices=[('not_sent', 'Não enviada'), ('pending', 'Em análise'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='pending', max_length=10),
        ),
    ]
