# Generated by Django 5.1.4 on 2026-08-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sellerkyc_document_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerkyc',
            name='document_back',
            field=models.FileField(blank=True, upload_to='kyc/documents/'),
        ),
        migrations.AlterField(
            model_name='sellerkyc',
            name='document_front',
            field=models.FileField(blank=True, upload_to='kyc/documents/'),
        ),
        migrations.AlterField(
            model_name='sellerkyc',
            name='selfie_with_document',
            field=models.FileField(blank=True, upload_to='kyc/selfies/'),
        ),
        migrations.AlterField(
            model_name='sellerkyc',
            name='status',
            field=models.CharField(choices=[('not_sent', 'Não enviada'), ('pending', 'Em análise'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='not_sent', max_length=10),
        ),
    ]
