# Generated by Django 5.1.4 on 2026-07-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_order_options_order_canceled_reason_and_more'),
        ('stores', '0004_simplified_intermediary'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='walletentry',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'sale_credit')), fields=('order', 'kind'), name='wallet_unique_sale_credit_per_order'),
        ),
    ]
