# Generated by Django 5.1.4 on 2026-08-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_order_shipping_payout_sent_at'),
        ('stores', '0004_simplified_intermediary'),
        ('wallet', '0002_walletentry_wallet_unique_sale_credit_per_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletentry',
            name='kind',
            field=models.CharField(choices=[('sale_credit', 'Crédito de venda (item)'), ('shipping_credit', 'Crédito de frete e embalagem'), ('withdrawal_debit', 'Débito de saque'), ('adjustment', 'Ajuste')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='walletentry',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'shipping_credit')), fields=('order', 'kind'), name='wallet_unique_shipping_credit_per_order'),
        ),
    ]
