# Generated by Django 5.1.4 on 2026-08-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_order_access_token_unique'),
        ('stores', '0007_store_origin_city_store_origin_complement_and_more'),
        ('wallet', '0003_alter_walletentry_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletentry',
            name='kind',
            field=models.CharField(choices=[('sale_credit', 'Crédito de venda (item)'), ('shipping_credit', 'Crédito de frete e embalagem'), ('referral_bonus', 'Bônus de indicação (vendas indicadas)'), ('withdrawal_debit', 'Débito de saque'), ('adjustment', 'Ajuste')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='walletentry',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'referral_bonus')), fields=('order', 'kind'), name='wallet_unique_referral_bonus_per_order'),
        ),
    ]
