# Generated by Django 5.1.4 on 2026-07-19 00:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("pac", "PAC"),
                            ("sedex", "SEDEX"),
                            ("sedex_10", "SEDEX 10"),
                            ("sedex_12", "SEDEX 12"),
                        ],
                        max_length=10,
                    ),
                ),
                ("tracking_code", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_posting", "Aguardando postagem"),
                            ("posted", "Postado"),
                            ("in_transit", "Em trânsito"),
                            ("delivered", "Entregue"),
                            ("returned", "Devolvido"),
                        ],
                        default="awaiting_posting",
                        max_length=20,
                    ),
                ),
                ("estimated_delivery_days", models.PositiveSmallIntegerField()),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("last_tracking_event", models.CharField(blank=True, max_length=200)),
                ("last_tracking_check_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment",
                        to="payments.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShippingQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_cep", models.CharField(max_length=8)),
                ("destination_cep", models.CharField(max_length=8)),
                ("weight_grams", models.PositiveIntegerField()),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("pac", "PAC"),
                            ("sedex", "SEDEX"),
                            ("sedex_10", "SEDEX 10"),
                            ("sedex_12", "SEDEX 12"),
                        ],
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("deadline_days", models.PositiveSmallIntegerField()),
                ("quoted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["origin_cep", "destination_cep", "weight_grams"],
                        name="shipping_sh_origin__4b218f_idx",
                    )
                ],
            },
        ),
    ]
