# Generated by Django 5.1.4 on 2026-07-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='buyer_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='buyer_disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='label_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='melhor_envio_order_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='service',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
