# Generated by Django 5.1.4 on 2026-08-02 02:41

from django.db import migrations, models


def mark_legacy_provider(apps, schema_editor):
    Shipment = apps.get_model("shipping", "Shipment")
    Shipment.objects.exclude(provider_order_id="").update(
        shipping_provider="legacy_melhor_envio"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_shipment_buyer_confirmed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='melhor_envio_order_id',
            new_name='provider_order_id',
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_provider',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='label_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.RunPython(mark_legacy_provider, migrations.RunPython.noop),
    ]
