# Generated by Django 5.1.4 on 2026-07-19 00:46

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_payment", "Aguardando pagamento"),
                            ("paid", "Pago"),
                            ("shipped", "Enviado"),
                            ("delivered", "Entregue"),
                            ("disputed", "Em disputa"),
                            ("canceled", "Cancelado"),
                            ("refunded", "Reembolsado"),
                        ],
                        default="awaiting_payment",
                        max_length=20,
                    ),
                ),
                ("items_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "shipping_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "platform_commission_percent",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="Congelado no pedido para nao mudar retroativamente com config futura.",
                    ),
                ),
                ("shipping_address", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="stores.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="payments.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="asaas", max_length=20)),
                ("provider_charge_id", models.CharField(blank=True, max_length=100)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("pix", "Pix"),
                            ("credit_card", "Cartão de crédito"),
                            ("debit_card", "Cartão de débito"),
                            ("boleto", "Boleto"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("confirmed", "Confirmado"),
                            ("failed", "Falhou"),
                            ("refunded", "Reembolsado"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "split_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="True quando o PSP confirma que o split para a subconta da vendedora foi feito.",
                    ),
                ),
                ("raw_webhook_payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="payments.order",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="payments_or_status_daab12_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["buyer", "status"], name="payments_or_buyer_i_d3300e_idx"
            ),
        ),
    ]
