# Generated by Django 5.1.4 on 2026-07-19 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payer_cpf_matched',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_document',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('order_commission', 'Comissão de intermediação (pedido)'), ('buyer_subscription', 'Assinatura de comprador'), ('store_plan', 'Plano de loja'), ('boost', 'Boost')], max_length=20)),
                ('reference_id', models.CharField(help_text='Cobrança/assinatura no PSP a que a NF se refere.', max_length=100)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_cpf', models.CharField(max_length=11)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor do serviço da plataforma.', max_digits=10)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Aguardando emissão'), ('issued', 'Emitida'), ('failed', 'Falhou')], default='pending', max_length=10)),
                ('provider_invoice_id', models.CharField(blank=True, max_length=100)),
                ('pdf_url', models.URLField(blank=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='payments.order')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'kind'], name='payments_in_status_d59397_idx')],
            },
        ),
    ]
