# Generated by Django 5.1.4 on 2026-07-19 15:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_payer_cpf_matched_payment_payer_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='platform_commission_percent',
        ),
        migrations.AddField(
            model_name='order',
            name='packaging_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Já somado a shipping_total - guardado à parte só para exibir o detalhamento ao comprador.', max_digits=6),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_payout_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
