# Generated by Django 5.1.4 on 2026-07-31 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_simplified_intermediary'),
        ('stores', '0004_simplified_intermediary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='canceled_reason',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_restored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='pix_copy_paste',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='pix_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='pix_qr_code',
            field=models.TextField(blank=True, help_text='Imagem do QR em data URL.'),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Aguardando pagamento'), ('paid', 'Pago'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('disputed', 'Em disputa'), ('canceled', 'Cancelado'), ('expired', 'Expirado (não pago)'), ('refunded', 'Reembolsado')], default='awaiting_payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_charge_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'expires_at'], name='payments_or_status_4fb679_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'status'], name='payments_or_store_i_4eef3d_idx'),
        ),
    ]
