# Generated by Django 5.1.4 on 2026-08-01 08:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_order_payout_sent_at_orderitem_addons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('buyer', 'Comprador'), ('seller', 'Vendedora')], max_length=6)),
                ('body', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='payments.order')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='payments_or_order_i_85542a_idx')],
            },
        ),
    ]
