# Generated by Django 5.1.4 on 2026-08-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_backfill_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_payout_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
