# Generated by Django 5.1.4 on 2026-08-02 02:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_order_shipping_payout_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='packaging_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Parcela da embalagem neutra embutida no frete. Com etiqueta pela plataforma, só este valor é creditado à vendedora; o restante do shipping_total compra a etiqueta.', max_digits=6),
        ),
    ]
