# Generated by Django 5.1.4 on 2026-08-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_order_packaging_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='access_token',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
