# Generated by Django 5.1.4 on 2026-07-19 10:26

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_product_reserved_for_product_visibility'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrderRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(help_text='Descrição do ITEM FÍSICO desejado (cor, tamanho, tempo de uso...).', max_length=2000)),
                ('offered_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('counter_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('counter_message', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Aguardando resposta'), ('countered', 'Contra-proposta enviada'), ('accepted', 'Aceito'), ('rejected', 'Recusado'), ('canceled', 'Cancelado')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_order_requests', to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_order_request', to='catalog.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_order_requests', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'status'], name='offers_cust_store_i_130573_idx'), models.Index(fields=['buyer', 'status'], name='offers_cust_buyer_i_f11086_idx')],
            },
        ),
    ]
