# Generated by Django 5.1.4 on 2026-07-19 00:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoostPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("duration_hours", models.PositiveIntegerField(default=24)),
            ],
        ),
        migrations.CreateModel(
            name="StorePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("duration_days", models.PositiveIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("display_name", models.CharField(max_length=80)),
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Aguardando moderação"),
                            ("active", "Ativa"),
                            ("suspended", "Suspensa"),
                            ("banned", "Banida"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("plan_expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("psp_subaccount_id", models.CharField(blank=True, max_length=100)),
                ("pix_key", models.CharField(blank=True, max_length=140)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stores",
                        to="stores.storeplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreBoost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ends_at", models.DateTimeField()),
                ("paid", models.BooleanField(default=False)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stores.boostpackage",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boosts",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ends_at"], name="stores_stor_ends_at_8cb67d_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(fields=["status"], name="stores_stor_status_d56e36_idx"),
        ),
    ]
