# Generated by Django 5.1.4 on 2026-07-19 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='origin_cep',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='store',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='stores.storeplan'),
        ),
        migrations.AlterField(
            model_name='store',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
