# Generated by Django 5.1.4 on 2026-07-19 19:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_origin_cep_alter_store_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3),
        ),
        migrations.AddField(
            model_name='store',
            name='bayesian_rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3),
        ),
        migrations.AddField(
            model_name='store',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='sales_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
