# Generated by Django 5.1.4 on 2026-07-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_avg_rating_store_bayesian_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='pix_key_type',
            field=models.CharField(blank=True, default='CPF', help_text='CPF, CNPJ, EMAIL, PHONE ou EVP (chave aleatoria).', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='psp_api_key',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
