# Generated by Django 5.1.4 on 2026-08-02 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_storefollow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storefollow',
            new_name='stores_stor_created_a61545_idx',
            old_name='stores_stor_created_idx',
        ),
    ]
