# Generated by Django 5.1.4 on 2026-08-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_rename_storefollow_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='origin_city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='store',
            name='origin_complement',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='store',
            name='origin_district',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='store',
            name='origin_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='origin_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='store',
            name='origin_street',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
